platform :ios, '7.0'
pod 'AFNetworking', '~> 2.6.3'
pod 'MJRefresh', '~> 3.0.8'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'YTKNetwork', '~> 0.5.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~>3.7.5'
pod 'PLCrashReporter', '~> 1.2.0'
pod 'SSKeychain', '~> 1.2.3’
#pod 'SSZipArchive', '~> 0.3.3'
pod 'NJKWebViewProgress'
#pod 'LBXScan', '~> 1.1.1'
#pod 'PNChart'
pod 'Masonry'
#pod 'PPiFlatSegmentedControl'
pod 'IQKeyboardManager'
pod 'libextobjc', '~> 0.4'
pod 'UITableView+FDTemplateLayoutCell'